### ISSUE TITLE
[Kotlin] Kotlin In Action 8장 정리

### ISSUE THREAD

**Issue by huisam** [Road-of-CODEr/we-hate-jvm#17]
## 8장 고차 함수

* 고차 함수
* 인라임 함수

에 대해서 정리해보록 하겠습니다~!

[참고 책](http://www.yes24.com/Product/Goods/55148593)

**Comment by juheekimm** [comment]
코틀린도 나중에 해야하는데.. 휘진님 글로 공부해야겠네요! 😃 ㅋㅋ
