### ISSUE TITLE
[Java] Java Basic theorem

### ISSUE THREAD

**Issue by kwj1270** [Road-of-CODEr/we-hate-jvm#23]
자바 기초 문법 + 심화 내용에 대해서 정리하겠습니다.  
   
1. JVM
    
심화 과정으로 공부했기 때문에       
서적, 입문서에 나온 내용뿐만 아니라, 더 깊은 내용들도 기술하려 합니다.     
이미 [기존에 11주차 까지 정리해 놓은 사이트](https://velog.io/@kwj1270/series/%EC%8A%A4%ED%84%B0%EB%94%94-%ED%95%A0%EB%9E%98)가 존재하기는 하지만, 
`기존에 작성한 내용` + `온라인 스터디 내용` + `다른 스터디원 내용`까지 합쳐서 다시 정리하고 올리겠습니다.

**Comment by J-minkuk** [comment]
다른 스터디원의 블로그 내용을 너무 복붙하지만 않으면 좋을 것 같습니다! 👍🏻

**Comment by kwj1270** [comment]
네 알겠습니다. 글부터 시작해서 코드까지 제가 다시 직접 정리해보겠습니다! 👍🏻
